services:
    _defaults:
        public: true  #TODO remove
        autowire: true
        autoconfigure: true

    FHPlatform\ConfigBundle\:
        resource: '../src/*'
        exclude: '../src/DTO/*'
