services:
    _defaults:
        public: true  #TODO remove
        autowire: true
        autoconfigure: true

    FHPlatform\ConfigBundle\:
        resource: '../src/*'
        exclude: '../src/DTO/*'

    FHPlatform\ConfigBundle\Provider\ConnectionsProvider:
        factory: ['FHPlatform\ConfigBundle\Factory\ConnectionsFactory', 'create']
        arguments:
            $connectionsBuilder: '@FHPlatform\ConfigBundle\Builder\ConnectionsBuilder'

    FHPlatform\ConfigBundle\Config\ConfigProvider:
        arguments:
            - !tagged fh_platform.config.connection
            - !tagged fh_platform.config.provider.index
            - !tagged fh_platform.config.provider.entity
            - !tagged fh_platform.config.provider.entity_related
            - !tagged fh_platform.config.decorator.index
            - !tagged fh_platform.config.decorator.entity
            - !tagged fh_platform.config.decorator.entity_related
