services:
    _defaults:
        public: true  #TODO remove
        autowire: true
        autoconfigure: true

    FHPlatform\ConfigBundle\:
        resource: '../src/*'
        exclude: '../src/DTO/*'

    FHPlatform\ConfigBundle\Provider\ConnectionsProvider:
        factory: ['FHPlatform\ConfigBundle\Factory\ConnectionsFactory', 'create']
        arguments:
            $connectionsBuilder: '@FHPlatform\ConfigBundle\Builder\ConnectionsBuilder'
