services:

    nginx:
        container_name: fh_platform_nginx
        build: ./.docker/nginx
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '5006:80'

    php:
        container_name: fh_platform_php
        build: ./.docker/php
        volumes:
            - ./:/var/www/html

    mysql:
        container_name: fh_platform_mysql
        build: ./.docker/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=fh_platform"
            - "MYSQL_USER=fh_platform"
            - "MYSQL_PASSWORD=fh_platform"
        volumes:
            - db-data-fh_platform:/var/lib/mysql
            - ./:/app
        ports:
            - "33308:3306"
    meilisearch:
        container_name: fh_platform_meilisearch
        build: ./.docker/meilisearch
        ports:
            - 7700:7700
        volumes:
            - 'fh_platform_meilisearch-data:/usr/share/meilisearch/data'
        environment:
            - MEILI_MASTER_KEY=root
    elasticsearch:
        container_name: fh_platform_elasticsearch
        build: ./.docker/elasticsearch
        environment:
            - node.name=elasticsearch
            - cluster.name=es-docker-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports: [ '9201:9200' ]
        volumes:
            - 'fh_platform_es-data:/usr/share/elasticsearch/data'

    elasticsearch2:
        container_name: fh_platform_elasticsearch2
        build: ./.docker/elasticsearch
        environment:
            - node.name=elasticsearch2
            - cluster.name=es-docker-cluster2
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports: [ '9202:9200' ]
        volumes:
            - 'fh_platform_es-data2:/usr/share/elasticsearch/data2'

    kibana:
        container_name: fh_platform_kibana
        build: ./.docker/kibana
        ports: [ '5603:5601' ]
        depends_on: [ 'elasticsearch' ]
        environment:
            - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    kibana2:
        container_name: fh_platform_kibana2
        build: ./.docker/kibana
        ports: [ '5604:5601' ]
        depends_on: [ 'elasticsearch2' ]
        environment:
            - "ELASTICSEARCH_HOSTS=http://elasticsearch2:9200"
volumes:
    fh_platform_es-data:
    fh_platform_es-data2:
    fh_platform_meilisearch-data:
    db-data-fh_platform:



