services:
    _defaults:
        autowire: true
        autoconfigure: true

    FHPlatform\Bundle\PersistenceDoctrineBundle\:
        resource: '../src/*'

    FHPlatform\Bundle\PersistenceDoctrineBundle\Persistence\PersistenceDoctrine:
        autowire: true
        public: true
