services:
    _defaults:
        autowire: true
        autoconfigure: true

    FHPlatform\Bundle\PersistenceDoctrineBundle\:
        resource: '../src/*'

    FHPlatform\Bundle\PersistenceDoctrineBundle\Helper\DoctrineHelper:
        autowire: true
        public: true
