services:
    _defaults:
        autowire: true
        autoconfigure: true

    FHPlatform\Bundle\SymfonyBridgeBundle\:
        resource: '../src/*'

    #define provider
    FHPlatform\Component\Client\Provider\ProviderInterface: '@FHPlatform\Component\ClientElastica\ElasticaProvider'

    #define persistence
    FHPlatform\Component\Persistence\Persistence\PersistenceInterface: '@FHPlatform\Bundle\PersistenceDoctrineBundle\Persistence\PersistenceDoctrine'

    #TODO
    FHPlatform\Component\Persistence\Event\EventDispatcher\EventDispatcher:
        public: true

    #TODO
    FHPlatform\Component\Persistence\Message\MessageHandler\EntitiesChangedMessageHandler:
        public: true
        autowire: true
        autoconfigure: true

    #TODO
    FHPlatform\Component\Persistence\Event\EventListener\EventListener:
        public: true
        autowire: true
        autoconfigure: true

    #TODO
    FHPlatform\Component\Persistence\Syncer\DataSyncer:
        public: true

    FHPlatform\Component\ClientElastica\ElasticaProvider:
        autowire: true
        autoconfigure: true

    FHPlatform\Component\ClientElastica\Connection\ConnectionFetcher:
        autowire: true
        autoconfigure: true

    FHPlatform\Component\Client\Provider\Index\IndexClient:
        public: true
        autowire: true
        autoconfigure: true

    FHPlatform\Component\Client\Provider\Query\QueryClient:
        public: true
        autowire: true
        autoconfigure: true

    FHPlatform\Component\Client\Provider\Data\DataClient:
        public: true
        autowire: true
        autoconfigure: true

    FHPlatform\Component\Config\Config\ConfigProvider:
        arguments:
            - !tagged fh_platform.config.connection
            - !tagged fh_platform.config.provider.index
            - !tagged fh_platform.config.provider.entity
            - !tagged fh_platform.config.provider.entity_related
            - !tagged fh_platform.config.decorator.index
            - !tagged fh_platform.config.decorator.entity
            - !tagged fh_platform.config.decorator.entity_related
        autowire: true
        autoconfigure: true
        public: true

    FHPlatform\Component\Config\Builder\ConnectionsBuilder:
        arguments:
            $configProvider: '@FHPlatform\Component\Config\Config\ConfigProvider'
        public: true

    FHPlatform\Component\Config\Builder\EntityBuilder:
        arguments:
            $configProvider: '@FHPlatform\Component\Config\Config\ConfigProvider'
            $connectionsBuilder: '@FHPlatform\Component\Config\Builder\ConnectionsBuilder'
            $persistenceDoctrine: '@FHPlatform\Bundle\PersistenceDoctrineBundle\Persistence\PersistenceDoctrine'
        public: true

    FHPlatform\Component\Config\Builder\EntitiesRelatedBuilder:
        arguments:
            $configProvider: '@FHPlatform\Component\Config\Config\ConfigProvider'
        public: true

    FHPlatform\Component\Config\Builder\IndexBuilder:
        arguments:
            $configProvider: '@FHPlatform\Component\Config\Config\ConfigProvider'
        public: true


