services:
    _defaults:
        autowire: true
        autoconfigure: true

    FHPlatform\Bundle\SymfonyBridgeBundle\:
        resource: '../src/*'

    #define persistence
    FHPlatform\Component\PersistenceDoctrine\Persistence\PersistenceDoctrine:
        autowire: true

    FHPlatform\Component\Persistence\Persistence\PersistenceInterface: '@FHPlatform\Component\PersistenceDoctrine\Persistence\PersistenceDoctrine'
    #define persistence

    #define provider
    FHPlatform\Component\ClientElastica\ElasticaProvider:
        autowire: true

    FHPlatform\Component\Client\Provider\ProviderInterface: '@FHPlatform\Component\ClientElastica\ElasticaProvider'
    #define provider

    #define dispatcher
    FHPlatform\Bundle\SymfonyBridgeBundle\Dispatcher\Dispatcher:
        autowire: true
    FHPlatform\Component\Persistence\Dispatcher\DispatcherInterface: '@FHPlatform\Bundle\SymfonyBridgeBundle\Dispatcher\Dispatcher'
    #define dispatcher


    #TODO
    FHPlatform\Component\Persistence\EventDispatcher\EventDispatcher:
        autowire: true
        public: true

    FHPlatform\Component\PersistenceDoctrine\Listener\DoctrineListener:
        public: true
        autoconfigure: true
        autowire: true
        tags:
            - { name: doctrine.event_listener, event: postPersist, priority: 10 }
            - { name: doctrine.event_listener, event: postUpdate, priority: 10 }
            - { name: doctrine.event_listener, event: postRemove, priority: 10 }
            - { name: doctrine.event_listener, event: preRemove, priority: 10 }
            - { name: doctrine.event_listener, event: postFlush, priority: 10 }
    #TODO
    FHPlatform\Component\Persistence\Message\MessageHandler\EntitiesChangedMessageHandler:
        public: true
        autowire: true
        autoconfigure: true

    #TODO
    FHPlatform\Component\Persistence\Event\EventListener\EventListener:
        public: true
        autowire: true
        autoconfigure: true

    #TODO
    FHPlatform\Component\Persistence\Syncer\DataSyncer:
        public: true

    FHPlatform\Component\ClientElastica\Connection\ConnectionFetcher:
        autowire: true
        autoconfigure: true

    FHPlatform\Component\Client\Provider\Index\IndexClient:
        public: true
        autowire: true
        autoconfigure: true

    FHPlatform\Component\Client\Provider\Query\QueryClient:
        public: true
        autowire: true
        autoconfigure: true

    FHPlatform\Component\Client\Provider\Data\DataClient:
        public: true
        autowire: true
        autoconfigure: true

    FHPlatform\Component\Config\Config\ConfigProvider:
        arguments:
            - !tagged fh_platform.config.connection
            - !tagged fh_platform.config.provider.index
            - !tagged fh_platform.config.provider.entity
            - !tagged fh_platform.config.provider.entity_related
            - !tagged fh_platform.config.decorator.index
            - !tagged fh_platform.config.decorator.entity
            - !tagged fh_platform.config.decorator.entity_related
        autowire: true
        autoconfigure: true
        public: true

    FHPlatform\Component\Config\Builder\ConnectionsBuilder:
        arguments:
            $configProvider: '@FHPlatform\Component\Config\Config\ConfigProvider'
        public: true

    FHPlatform\Component\Config\Builder\EntityBuilder:
        arguments:
            $configProvider: '@FHPlatform\Component\Config\Config\ConfigProvider'
            $connectionsBuilder: '@FHPlatform\Component\Config\Builder\ConnectionsBuilder'
            $persistence: '@FHPlatform\Component\Persistence\Persistence\PersistenceInterface'
        public: true

    FHPlatform\Component\Config\Builder\EntitiesRelatedBuilder:
        arguments:
            $configProvider: '@FHPlatform\Component\Config\Config\ConfigProvider'
        public: true

    FHPlatform\Component\Config\Builder\IndexBuilder:
        arguments:
            $configProvider: '@FHPlatform\Component\Config\Config\ConfigProvider'
        public: true


