services:
    FHPlatform\Bundle\SymfonyBridgeBundle\Command\:
        resource: '../src/Command/*'
        autowire: true
        autoconfigure: true

    #TODO
    FHPlatform\Component\DoctrineToEs\:
        resource: '../../../Component/DoctrineToEs/src/'
        autowire: true
        autoconfigure: true

