services:

    nginx:
        container_name: basic_nginx
        build: ./.docker/nginx
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '5004:80'

    php:
        container_name: basic_php
        build: ./.docker/php
        volumes:
            - ./:/var/www/html

    mysql:
        container_name: basic_mysql
        build: ./.docker/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=basic"
            - "MYSQL_USER=basic"
            - "MYSQL_PASSWORD=basic"
        volumes:
            - db-data-basic:/var/lib/mysql
            - ./:/app
        ports:
            - "33308:3306"

volumes:
    db-data-basic:
