parameters:
    test: '%env(TEST)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/App/'
        exclude:
            - '../src/App/Entity/'
            - '../src/App/Kernel.php'

