services:
    _defaults:
        autowire: true
        autoconfigure: true

    FHPlatform\ConfigBundle\:
        resource: '../src/*'

    FHPlatform\ConfigBundle\Finder\ProviderFinder:
        public: true

